### ISSUE TITLE
pulse

### ISSUE THREAD

**Issue by yegor256** [yegor256/sixnines#36]
Let's show our current rate of pinging endpoints, to make sure we're alive. Let's just increment some global counter and show that counter on the front page. Let's update it via JavaScript, every second.

**Comment by yegor256** [comment]
@0crat assign @pdacostaporto

**Comment by 0crat** [comment]
+15 points just awarded to @yegor256, total is [+1560](http://www.0crat.com/u/yegor256).

**Comment by pdacostaporto** [comment]
@yegor256 check #85

**Comment by pdacostaporto** [comment]
@yegor256 close this if you think it's done

**Comment by yegor256** [comment]
@pdacostaporto thanks!

**Comment by 0crat** [comment]
Job `gh:yegor256/sixnines#36` is now out of scope.

**Comment by 0crat** [comment]
+30 points just awarded to @pdacostaporto, total is [+225](http://www.0crat.com/u/pdacostaporto).
