### ISSUE TITLE
cookie.rb:29-31: We are not encrypting cooking anyhow...

### ISSUE THREAD

**Issue by 0pdd** [yegor256/sixnines#40]
The puzzle `1-e122d8f8` in [`objects/cookie.rb`](https://github.com/yegor256/sixnines/blob/master/objects/cookie.rb) (lines 29-31) has to be resolved: We are not encrypting cooking anyhow at the moment and this is not secure at all. Let's introduce some encryption mechanism with a secret key.

The puzzle was created by Yegor Bugayenko on 07-Apr-17. 

Estimate: 30 minutes, role: IMP.

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is removed from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html).

**Comment by 0pdd** [comment]
The puzzle `1-e122d8f8` has disappeared from the source code, that's why I closed this issue.

**Comment by 0crat** [comment]
Oops! Job `gh:yegor256/sixnines#40` was not in scope
