### ISSUE TITLE
w3c compliance

### ISSUE THREAD

**Issue by yegor256** [yegor256/sixnines#57]
See https://validator.w3.org/nu/?doc=http%3A%2F%2Fwww.sixnines.io%2F

And this https://validator.w3.org/nu/?doc=http%3A%2F%2Fwww.sixnines.io%2Fh%2Fe203

**Comment by yegor256** [comment]
@0crat assign @pdacostaporto

**Comment by 0crat** [comment]
> @0crat assign @pdacostaporto ([here](https://github.com/yegor256/sixnines/issues/57#issuecomment-321804553))

@yegor256 Job `gh:yegor256/sixnines#57` assigned to @pdacostaporto, please go ahead ([policy](http://datum.zerocracy.com/pages/policy.html)).

**Comment by 0crat** [comment]
+15 points just awarded to @yegor256, total is [+1575](http://www.0crat.com/u/yegor256).

**Comment by 0crat** [comment]
@pdacostaporto this job was assigned to you 8 days ago.
It will be taken away from you after 10 days from start (this is our policy).

**Comment by 0crat** [comment]
@pdacostaporto resigned from `gh:yegor256/sixnines#57`, please stop working.

**Comment by 0crat** [comment]
Oops! Job `gh:yegor256/sixnines#57` is not assigned to anyone.

**Comment by 0crat** [comment]
Oops! Job `gh:yegor256/sixnines#57` is not assigned to anyone.

**Comment by 0crat** [comment]
Oops! Job `gh:yegor256/sixnines#57` is not assigned to anyone.

**Comment by 0crat** [comment]
Oops! Job `gh:yegor256/sixnines#57` is not assigned to anyone.

**Comment by 0crat** [comment]
@pdacostaporto resigned from `gh:yegor256/sixnines#57`, please stop working.

**Comment by 0crat** [comment]
Job `gh:yegor256/sixnines#57` assigned to @pdacostaporto. The budget is [fixed](http://datum.zerocracy.com/pages/policy.html#4) and it is 30 minutes. Please, read the [Policy](http://datum.zerocracy.com/pages/policy.html) and go ahead.

**Comment by 0crat** [comment]
@pdacostaporto resigned from `gh:yegor256/sixnines#57`, please stop working.

**Comment by yegor256** [comment]
@0crat refuse

**Comment by yegor256** [comment]
@rultor release, tag is `0.21.7`

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/yegor256/sixnines/issues/57#issuecomment-497198616))

@yegor256 Job `gh:yegor256/sixnines#57` is not assigned, can't get performer

**Comment by 0crat** [comment]
Job `gh:yegor256/sixnines#57` is not assigned, can't get performer

**Comment by 0crat** [comment]
The job [#57](https://github.com/yegor256/sixnines/issues/57) is now out of scope
