### ISSUE TITLE
hide non-relevant points from the graph

### ISSUE THREAD

**Issue by yegor256** [yegor256/sixnines#62]

**Comment by yegor256** [comment]
@rultor release, tag is `0.14.1`

**Comment by yegor256** [comment]
@rultor release, tag is `0.14.1`

**Comment by yegor256** [comment]
@rultor release, tag is `0.14.1`

**Comment by yegor256** [comment]
@rultor release, tag is `0.14.1`

**Comment by yegor256** [comment]
@rultor release, tag is `0.14.1`

**Comment by yegor256** [comment]
@rultor release, tag is `0.14.1`

**Comment by yegor256** [comment]
@rultor release, tag is `0.14.1`

**Comment by yegor256** [comment]
@rultor release, tag is `0.14.1`

**Comment by yegor256** [comment]
@rultor stop

**Comment by yegor256** [comment]
@rultor release, tag is `0.14.1`

**Comment by yegor256** [comment]
@rultor release, tag is `0.14.1`

**Comment by yegor256** [comment]
@rultor release, tag is `0.14.1`

**Comment by yegor256** [comment]
@rultor release, tag is `0.14.1`

**Comment by yegor256** [comment]
@rultor release, tag is `0.14.1`

**Comment by 0crat** [comment]
Oops! Job `gh:yegor256/sixnines#62` was not in scope
