### ISSUE TITLE
Consider another logo

### ISSUE THREAD

**Issue by amihaiemil** [yegor256/sixnines#64]
The leaf logo looks too much like the Spring and baeldung.com logos, in my opinion. :D

**Comment by 0crat** [comment]
@yegor256 please, pay attention to this issue

**Comment by yegor256** [comment]
@amihaiemil yes, it's close, but not exactly the same :) But thanks for mentioning it. We'll think it over.

**Comment by yegor256** [comment]
@amihaiemil we decided to stay with the current logo :)
