### ISSUE TITLE
badges are black in Safari and on iPhone

### ISSUE THREAD

**Issue by yegor256** [yegor256/sixnines#65]
<img width="1080" alt="screen shot 2017-04-23 at 8 38 16 am" src="https://cloud.githubusercontent.com/assets/526301/25343145/d5a60fb0-2916-11e7-835b-23e46d1d5440.png">

**Comment by yegor256** [comment]
fixed in #66

**Comment by 0crat** [comment]
Oops! Job `gh:yegor256/sixnines#65` was not in scope
