### ISSUE TITLE
Pages for sites are not available with 503 error

### ISSUE THREAD

**Issue by spitty** [yegor256/sixnines#72]
Currently any link to specific site (e.g. http://www.sixnines.io/h/3ba1652f) shows 503 error with next stacktrace:

```
undefined local variable or method `user' for #
    /app/views/history.haml:5:in `block in singleton class'
    /app/views/history.haml:-14:in `instance_eval'
    /app/views/history.haml:-14:in `singleton class'
    /app/views/history.haml:-16:in `__tilt_69920103355600'
<...>
```

It points to this line: https://github.com/yegor256/sixnines/blob/master/views/history.haml#L5

**Comment by 0crat** [comment]
@yegor256 please, pay attention to this issue

**Comment by yegor256** [comment]
@spitty thanks for reporting, let me fix it

**Comment by yegor256** [comment]
@rultor release, tag is `0.16.1`

**Comment by 0crat** [comment]
@yegor256 please, ask @spitty to close this issue and [read more](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html)

**Comment by 0crat** [comment]
@yegor256 please, pay attention to this issue

**Comment by yegor256** [comment]
@spitty please, check again, should work just fine

**Comment by spitty** [comment]
@yegor256 
It works properly. Thank you.

**Comment by 0crat** [comment]
Oops! Job `gh:yegor256/sixnines#72` was not in scope
