### ISSUE TITLE
any 20x response code is OK

### ISSUE THREAD

**Issue by yegor256** [yegor256/sixnines#73]
Let's treat them all as OK

**Comment by yegor256** [comment]
@rultor release, tag is `0.18`

**Comment by yegor256** [comment]
@rultor release, tag is `0.18`

**Comment by yegor256** [comment]
@rultor release, tag is `0.18`

**Comment by yegor256** [comment]
@rultor release, tag is `0.18`

**Comment by 0crat** [comment]
Oops! Job `gh:yegor256/sixnines#73` was not in scope
