### ISSUE TITLE
Proxy authentication required.

### ISSUE THREAD

**Issue by yegor256** [yegor256/sixnines#90]
`Proxy authentication required.` is not a valid cause of failure!

**Comment by 0crat** [comment]
Job `gh:yegor256/sixnines#90` assigned to @yegor256, please go ahead ([policy](http://datum.zerocracy.com/pages/policy.html)).

**Comment by 0crat** [comment]
+15 points just awarded to @yegor256, total is [+3150](http://www.0crat.com/u/yegor256).

**Comment by yegor256** [comment]
@rultor release, tag is `0.20.1`

**Comment by 0crat** [comment]
Job `gh:yegor256/sixnines#90` is now out of scope.

**Comment by 0crat** [comment]
+30 points just awarded to @yegor256, total is [+3180](http://www.0crat.com/u/yegor256).
