### ISSUE TITLE
Cannot change target URL in case of protocol/prefix mismatch

### ISSUE THREAD

**Issue by SilasReinagel** [yegor256/sixnines#93]
Should not be charged another one-time setup fee while trying to correctly configure the URL for a site. User should be allowed to tune the URL until at least one success occurs, or within a certain configuration window.

Presently, my site is getting a 301 Redirect if I prefix with `www`, and I can't change the URL. I only have the option to create a new site or delete my existing site. 

This is a terrible user experience!

**Comment by SilasReinagel** [comment]
@yegor256 Pay attention to this issue.

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @silasreinagel[/z](https://www.0crat.com/u/silasreinagel)

**Comment by 0crat** [comment]
The job [#93](https://github.com/yegor256/sixnines/issues/93) assigned to @pdacostaporto[/z](https://www.0crat.com/u/pdacostaporto), here is [why](https://www.0crat.com/footprint/C6MATTB7E/8880ec46-ecdb-4c9d-a06b-420e05c4956d); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by 0crat** [comment]
@pdacostaporto[/z](https://www.0crat.com/u/pdacostaporto) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by pdacostaporto** [comment]
@0crat wait for #96 .

**Comment by 0crat** [comment]
> @0crat wait for #96 . ([here](https://github.com/yegor256/sixnines/issues/93#issuecomment-451348450))

@pdacostaporto The impediment for [#93](https://github.com/yegor256/sixnines/issues/93) was registered successfully by @pdacostaporto[/z](https://www.0crat.com/u/pdacostaporto)

**Comment by yegor256** [comment]
@rultor release, tag is `0.21.0`

**Comment by yegor256** [comment]
@SilasReinagel I believe it's fixed. @pdacostaporto thanks a lot!

**Comment by 0crat** [comment]
The job [#93](https://github.com/yegor256/sixnines/issues/93) is now out of scope

**Comment by 0crat** [comment]
Order was finished: +30 point(s) just awarded to @pdacostaporto[/z](https://www.0crat.com/u/pdacostaporto)

**Comment by 0pdd** [comment]
@SilasReinagel the puzzle [#101](https://github.com/yegor256/sixnines/issues/101) is still not solved.

**Comment by 0pdd** [comment]
@SilasReinagel the puzzle [#unknown]() is still not solved.
