### ISSUE TITLE
Badges appears yellow even above 99.5% uptime

### ISSUE THREAD

**Issue by SilasReinagel** [yegor256/sixnines#94]
![image](https://user-images.githubusercontent.com/10834339/42615376-d1ab3d72-855e-11e8-9f6e-75c13b16baf3.png)

Badge should either be green above 99.5%, or it should be configurable for each monitored site, by the owner of the counter.

**Comment by SilasReinagel** [comment]
@yegor256 Pay attention to this issue.

**Comment by yegor256** [comment]
@SilasReinagel well, the schedule is different. We put green only when it's 99.9+.

**Comment by 0crat** [comment]
Job `gh:yegor256/sixnines#94` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
